version: "3.8"

services:
  lasu-hall-management:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    container_name: lasu-hall-management
